# ============================================
# Output Variables
# ============================================

# EKS Outputs
output "cluster_name" {
  description = "EKS cluster name"
  value       = module.eks.cluster_name
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster"
  value       = module.eks.cluster_security_group_id
}

# VPC Outputs
output "vpc_id" {
  description = "VPC ID"
  value       = module.vpc.vpc_id
}

output "private_subnets" {
  description = "List of private subnet IDs"
  value       = module.vpc.private_subnets
}

output "public_subnets" {
  description = "List of public subnet IDs"
  value       = module.vpc.public_subnets
}

output "database_subnets" {
  description = "List of database subnet IDs"
  value       = module.vpc.database_subnets
}

# RDS Outputs
output "rds_host" {
  description = "RDS host"
  value       = module.rds.db_instance_address
  sensitive   = true
}

output "rds_port" {
  description = "RDS port"
  value       = module.rds.db_instance_port
}

output "rds_database_name" {
  description = "RDS database name"
  value       = module.rds.db_instance_name
}

# Redis Outputs
output "redis_host" {
  description = "Redis host"
  value       = aws_elasticache_cluster.redis.cache_nodes[0].address
  sensitive   = true
}

output "redis_port" {
  description = "Redis port"
  value       = aws_elasticache_cluster.redis.port
}

# S3 Outputs
output "s3_bucket_name" {
  description = "S3 bucket name for images"
  value       = aws_s3_bucket.images.bucket
}

output "s3_bucket_arn" {
  description = "S3 bucket ARN for images"
  value       = aws_s3_bucket.images.arn
}



# Secrets Outputs
output "secrets_arns" {
  description = "ARNs of all secrets"
  value = {
    database = aws_secretsmanager_secret.database.arn
    redis    = aws_secretsmanager_secret.redis.arn
    s3       = aws_secretsmanager_secret.s3.arn
    services = aws_secretsmanager_secret.services.arn
  }
  sensitive = true
}

# IRSA Outputs
output "irsa_role_arns" {
  description = "ARNs of all IRSA roles"
  value = {
    external_secrets = module.irsa_external_secrets.iam_role_arn
    cert_manager     = module.irsa_cert_manager.iam_role_arn
    nginx_ingress    = module.irsa_nginx_ingress.iam_role_arn
    prometheus       = module.irsa_prometheus.iam_role_arn
    grafana          = module.irsa_grafana.iam_role_arn
    api_service      = module.irsa_api_service.iam_role_arn
    auth_service     = module.irsa_auth_service.iam_role_arn
    image_service    = module.irsa_image_service.iam_role_arn
  }
  sensitive = true
}

# Addons Outputs
output "addons_deployed" {
  description = "List of deployed Kubernetes addons"
  value = {
    external_secrets = var.enable_external_secrets ? "enabled" : "disabled"
    cert_manager     = var.enable_cert_manager ? "enabled" : "disabled"
    nginx_ingress    = var.enable_nginx_ingress ? "enabled" : "disabled"
    prometheus_stack = var.enable_prometheus_stack ? "enabled" : "disabled"
    metrics_server   = var.enable_metrics_server ? "enabled" : "disabled"
    cloudwatch_agent = var.enable_cloudwatch_agent ? "enabled" : "disabled"
  }
}

# Network Outputs
output "vpc_cidr" {
  description = "VPC CIDR block"
  value       = module.vpc.vpc_cidr_block
}

output "availability_zones" {
  description = "List of availability zones"
  value       = module.vpc.azs
}

# Kubeconfig
output "kubeconfig" {
  description = "kubectl config as generated by the module"
  value       = module.eks.kubeconfig
  sensitive   = true
}

# Load Balancer Outputs
output "nginx_ingress_hostname" {
  description = "Nginx Ingress Load Balancer hostname"
  value = try(
    helm_release.nginx_ingress[0].status == "deployed" ? 
    data.kubernetes_service.nginx_ingress[0].status[0].load_balancer[0].ingress[0].hostname : 
    null,
    null
  )
}

# Data source to get Nginx Ingress Load Balancer
data "kubernetes_service" "nginx_ingress" {
  count = var.enable_nginx_ingress ? 1 : 0

  metadata {
    name      = "nginx-ingress-controller"
    namespace = "ingress-nginx"
  }

  depends_on = [helm_release.nginx_ingress]
}